using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Enums {

	public enum Color { ORANGE, WHITE, RED, BLUE, NONE };

	public enum ResourceType { ORE, LUMBER, WOOL, BRICK, GRAIN, NONE };

	public enum CommodityType { CLOTH, COIN, PAPER, NONE };

	public enum PieceType { ROAD, SETTLEMENT, CITY, KNIGHT, 
		PIRATE, ROBBER, MERCHANT };

	public enum Status { ACTIVE, INACTIVE };

	public enum DevChartType { TRADE, POLITICS, SCIENCE };

	public enum GamePhase { SETUP_ONE, SETUP_TWO, PHASE_ONE, PHASE_TWO };

	public enum EventDie { BARBARIAN, TRADE, POLITICS, SCIENCE };

	public enum BarbarianStatus { HERE, THERE };

	public enum HexType { GOLD, WATER, DESERT, FOREST, PASTURE,
		FIELD, HILL, MOUNTAIN };

	public enum TurnOrder { FIRST, SECOND, THIRD, FOURTH };

	public enum TerrainType { LAND, WATER };

	public enum ProgressCardName { ALCHEMIST, CRANE, ENGINEER, INVENTOR,
		IRRIGATION, MEDICINE, MINING, PRINTER, ROADBUILDING, 
		SMITH, BISHOP, CONSTITUTION, DESERTER, DIPLOMAT, INTRIGUE, 
		SABOTEUR, SPY, WARLORD, WEDDING, COMMERCIALHARBOR, 
		MASTERMERCHANT, MERCHANT, MERCHANTFLEET,
		RESOURCEMONOPOLY, TRADEMONOPOLY };

	public enum PortType { NONE, GENERIC, ORE, LUMBER, WOOL, BRICK, GRAIN };

	public enum MoveType { MOVE_KNIGHT, DISPLACE_KNIGHT, UPGRADE_KNIGHT, 
		ACTIVATE_KNIGHT, BUILD_SETTLEMENT, BUILD_CITY, BUILD_CITY_WALL,
		BUILD_KNIGHT, BUILD_ROAD, BUILD_SHIP, MOVE_SHIP, CHASE_ROBBER, PLACE_INITIAL_SETTLEMENT,
		PLACE_INITIAL_CITY, PLACE_INITIAL_ROAD, PLACE_INITIAL_SHIP, SPECIAL, NONE}

	public enum Special {KNIGHT_DISPLACED, DISCARD_RESOURCE, DISCARD_PROGRESS,
		NONE}
}
